theme: jekyll-theme-minimal
title: My page
description: A simple attempt at cv website
logo: profile.jpg
show_downloads: False
navigation:
  - title: Home
    url: /
  - title: CV
    url: cv.md
  - title: Research
    url: research.md
  - title: Journalism
    url: journalism.md
